#!/usr/bin/env bash
# Scans assets/projects/*/ and writes _data/project_media.yml
# Run before committing after adding/removing media files.

set -euo pipefail
cd "$(dirname "$0")"

OUT="_data/project_media.yml"
echo "# Auto-generated by sync-media.sh — do not edit" > "$OUT"

for dir in assets/projects/*/; do
  [ -d "$dir" ] || continue
  folder=$(basename "$dir")

  files=$(find "$dir" -maxdepth 1 -type f \( \
    -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' \
    -o -iname '*.gif' -o -iname '*.webp' \
    -o -iname '*.mp4' -o -iname '*.webm' \
  \) | sort)

  [ -z "$files" ] && continue

  echo "" >> "$OUT"
  echo "${folder}:" >> "$OUT"

  while IFS= read -r filepath; do
    filename=$(basename "$filepath")
    ext="${filename##*.}"
    ext_lower=$(echo "$ext" | tr '[:upper:]' '[:lower:]')

    case "$ext_lower" in
      mp4|webm) type="video" ;;
      *)        type="image" ;;
    esac

    echo "  - file: $filename" >> "$OUT"
    echo "    type: $type" >> "$OUT"
  done <<< "$files"
done

echo "Wrote $OUT"
